controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

gz_ros_control:
  ros__parameters:
    hold_joints: false
    position_proportional_gain: 0.5
