controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

pidf_controller:
  ros__parameters:
    type: pid_controller/PidController 
    dof_names:
      - fl_hip_joint
      - fl_knee_joint

    command_interface: effort

    reference_and_state_interfaces:
      - position
      - velocity

    gains:
      fl_hip_joint:   {"p": 35.0, "i": 0.0, "d": 1.0, "i_clamp_min": -.inf, "i_clamp_max": .inf, "antiwindup_strategy":'none', "feedforward_gain": 0.0}
      fl_knee_joint:  {"p": 35.0, "i": 0.0, "d": 1.0, "i_clamp_min": -.inf, "i_clamp_max": .inf, "antiwindup_strategy":'none', "feedforward_gain": 0.0}

gz_ros_control:
  ros__parameters:
    hold_joints: false
    # position_proportional_gain: 0.5
