controller_manager:
  ros__parameters:
    update_rate: 10000  # 1kHz control loop

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # CHANGED: Registering the new controller type
    leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController

leg_controller:
  ros__parameters:
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    joints:
      - fr_hip_joint
      - fr_knee_joint
    
    allow_nonzero_velocity_at_trajectory_end: true
    # Critical for ensuring your P/D gains are actually used
    open_loop_control: false
    allow_partial_joints_goal: false

    gains:
      fr_hip_joint:
        p: 5.0
        d: 10.0
        i: 0.0
        ff_velocity_scale: 0.0  # This makes torque proportinal to velocity to counter backEMF and other creepies
      fr_knee_joint:
        p: 5.0
        d: 10.0
        i: 0.0
        ff_velocity_scale: 0.0

    constraints:
      stopped_velocity_tolerance: 0.01
      fr_hip_joint:
        has_effort_limits: true
        max_effort: 120.0  # Limit in Newton-meters
      fr_knee_joint:
        has_effort_limits: true
        max_effort: 120.0

gz_ros_control:
  ros__parameters:
    hold_joints: false
